sudo: false
language: node_js
node_js:
  - "0.10.30"

branches:
  only:
    - master

addons:
  postgresql: "9.3"

before_install:
  # Position ourselves to start the test in "script" phase
  - cd ~/build/cbclmicah/grasshopper

  # Configure postgres
  - psql -c 'create database grasshoppertest;' -U postgres
  - psql grasshoppertest -c 'create extension pg_trgm;' -U postgres
  - printf "\n\nconfig.db.username = 'postgres';" >> config.js

script:
  - grunt test-coverage-coveralls

notifications:
  email:
  - micah+github@cbcl.co.uk
